name: enjoy_nt
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  config:
    path: config
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  kt_dart: ^1.1.0
  provider: ^6.0.5
  responsive_framework: ^1.1.1
  rxdart: ^0.27.7
  uuid: ^4.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  flutter_onboarding_slider: ^1.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/icons/
    - assets/avatars/
    - assets/images/


